### PR TITLE
Prepare for new Yeoman Generator prompt()s.

### PR DESCRIPTION
**Pull request by stephenplusplus**
RE: https://github.com/yeoman/generator/pull/250

The Yeoman Generator has implemented a new prompt library, and as the release is imminent. See the above link, as well as [Inquirer](https://github.com/SBoudrias/Inquirer.js), to see the new library.

This PR should make the transition seamless :)

### CODE REVIEW

**Comment by romainberger** [comment]
Looks nice, thanks. I'll take a closer look and try it asap to merge it.

**Comment by stephenplusplus** [comment]
Cool! The new system is pretty nice. Hopefully I at least gave you a head start, should you need to make any tweaks :)

**Comment by romainberger** [comment]
Do you know if the new prompt library is available in the latest yo version on npm?
I'm getting an error on https://github.com/stephenplusplus/yeoman-wordpress/commit/13844ef2b420d1613f15fa00b416e26ae74e8071#L0R119

```
/usr/local/lib/node_modules/generator-yo-wordpress/app/index.js:121
    self.themeNameOriginal = props.themeName
                                  ^
TypeError: Cannot read property 'themeName' of null
```

If I use the error parameter it works:

```
this.prompt(prompts, function(e, props) {
    if(e) { return self.emit('error', e) }

    // ...
```

I've just updated everything (yeoman-generator@0.11.4 and yo@1.0.0-beta.6)

**Comment by stephenplusplus** [comment]
The new prompt library will be coming with `yeoman-generator`, but it's not part of `0.11.4`. If you try it against master, it should work. Long story short, the new prompts should be shipping sometime this week, I believe.

**Comment by romainberger** [comment]
Great, thanks for the info. I'll merge everything and wait for the next yeoman-generator to be published to ship it then.

**Pull request merged**
