### PR TITLE
Update theme name in SCSS pages for _s theme

### PR DESCRIPTION
**Pull request by bryanstedman**
I hope you don't mind that I continued to play around with this. 

I added a small feature where, if the user is using the default starter theme, _s, then the
theme name is updated in all of the SCSS files. Right now the CSS files remain unchanged.

### CODE REVIEW

**Comment by romainberger** [comment]
Sure I don't mind! Changing the theme name is a good idea, but why would this be done only if the user is using the _s theme, we could do the same with any theme, right?

**Comment by bryanstedman** [comment]
Yes, I totally agree. I just started with the _s theme, because it made my search/replace a bit easier. I have updated it now to include any theme. 

**Further improvements I'd like to make include:**
I'd like to add options at set up for Author, Author URI and Description. Then we can pull those into the stylesheets as well. I'd also like to include these changes in the CSS files. I'll try to work on this tomorrow if it sounds good to you.

**Comment by romainberger** [comment]
Thanks for the last commit, I can't test it right now but I will take a closer look at what you've done tomorrow morning.

For the others improvements, these are good ideas but I am afraid this could become annoying if there are too much questions when the user wants to start a project. I may be wrong though, it would be great to have feedback from other users.
Or it would be great to be able to store some general configuration for the author name and URI so it would not be asked every time. And the user always has the ability to change it directly so it's not a problem. What do you think?

And for the idea of applying those changes to the css files, I don't know if this is necessary as they are supposed to be compressed in the build process (there are not because the build task is broken but I guess you see what I mean), so these comments won't stay.

**Comment by bryanstedman** [comment]
I hear you about wanting to keep the initial setup as limited as possible. And I had a similar concern, but I figure that the user is going to have to type that stuff out anyway so we may as well get it at start so that when they go to activate the theme it is already named. This comment block is really important because, Wordpress uses it to pull in the info about the theme.  I really like your idea of having a way to set a general config, but I would then vote for still having the prompt and just offering these as the default options. 

You bring up a good point about the CSS files. My thinking was that it would be good to have the theme already named in the backend when the user goes to activate it, but as long as they use the yeoman server command than that will take care of that. 

You also mentioned that these comments are removed during the build process. I agree that the files should be compressed and comments removed, but this comment block in style.css is an exception. It must stay even after compression so that wordpress can still recognize the theme. It looks like compass will keep comments that start with "/*!" I played around with that a little, but didn't have much success. Anyway, do keep that in mind as you work on the build process. Also, If I can be of any help on that let me know.

**Comment by romainberger** [comment]
> I would then vote for still having the prompt and just offering these as the default options.

This sounds good to me.
And for the css files, you're right we have to change the infos because it's the file Wordpress uses, so if we just change the scss it won't have any effect. I did the modification in my last commit.

For the build script I started working on that in the build_script branch, it has been discussed in this issue if you want to take a look: https://github.com/romainberger/yeoman-wordpress/issues/6

**Pull request merged**
